// // To parse this JSON data, do
// //
// //     final freeQuranData = freeQuranDataFromJson(jsonString);
//
// import 'dart:convert';
//
// import 'package:azan_guru_mobile/ui/model/media_node.dart';
//
// FreeQuranData freeQuranDataFromJson(String str) =>
//     FreeQuranData.fromJson(json.decode(str));
//
// String freeQuranDataToJson(FreeQuranData data) => json.encode(data.toJson());
//
// class FreeQuranData {
//   List<FreeQuranNode>? nodes;
//
//   FreeQuranData({
//     this.nodes,
//   });
//
//   factory FreeQuranData.fromJson(Map<String, dynamic> json) => FreeQuranData(
//         nodes: json["nodes"] == null
//             ? []
//             : List<FreeQuranNode>.from(
//                 json["nodes"]!.map((x) => FreeQuranNode.fromJson(x))),
//       );
//
//   Map<String, dynamic> toJson() => {
//         "nodes": nodes == null
//             ? []
//             : List<dynamic>.from(nodes!.map((x) => x.toJson())),
//       };
// }
//
// class FreeQuranNode {
//   String? id;
//   int? databaseId;
//   DateTime? date;
//   String? title;
//   ListenQuran? listenQuran;
//
//   FreeQuranNode({
//     this.id,
//     this.databaseId,
//     this.date,
//     this.title,
//     this.listenQuran,
//   });
//
//   factory FreeQuranNode.fromJson(Map<String, dynamic> json) => FreeQuranNode(
//         id: json["id"],
//         databaseId: json["databaseId"],
//         date: json["date"] == null ? null : DateTime.parse(json["date"]),
//         title: json["title"],
//         listenQuran: json["listenQuran"] == null
//             ? null
//             : ListenQuran.fromJson(json["listenQuran"]),
//       );
//
//   Map<String, dynamic> toJson() => {
//         "id": id,
//         "databaseId": databaseId,
//         "date": date?.toIso8601String(),
//         "title": title,
//         "listenQuran": listenQuran?.toJson(),
//       };
// }
//
// class ListenQuran {
//   String? listenQuranDescription;
//   QuranAudio? quranAudio;
//
//   ListenQuran({
//     this.listenQuranDescription,
//     this.quranAudio,
//   });
//
//   factory ListenQuran.fromJson(Map<String, dynamic> json) => ListenQuran(
//         listenQuranDescription: json["listenQuranDescription"],
//         quranAudio: json["quranAudio"] == null
//             ? null
//             : QuranAudio.fromJson(json["quranAudio"]),
//       );
//
//   Map<String, dynamic> toJson() => {
//         "listenQuranDescription": listenQuranDescription,
//         "quranAudio": quranAudio?.toJson(),
//       };
// }
//
// class QuranAudio {
//   MediaNode? node;
//
//   QuranAudio({
//     this.node,
//   });
//
//   factory QuranAudio.fromJson(Map<String, dynamic> json) => QuranAudio(
//         node: json["node"] == null ? null : MediaNode.fromJson(json["node"]),
//       );
//
//   Map<String, dynamic> toJson() => {
//         "node": node?.toJson(),
//       };
// }
//
// // class QuranAudioNode {
// //   int? mediaItemId;
// //   String? mediaItemUrl;
// //   String? description;
//
// //   QuranAudioNode({
// //     this.mediaItemId,
// //     this.mediaItemUrl,
// //     this.description,
// //   });
//
// //   factory QuranAudioNode.fromJson(Map<String, dynamic> json) => QuranAudioNode(
// //         mediaItemId: json["mediaItemId"],
// //         mediaItemUrl: json["mediaItemUrl"],
// //         description: json["description"],
// //       );
//
// //   Map<String, dynamic> toJson() => {
// //         "mediaItemId": mediaItemId,
// //         "mediaItemUrl": mediaItemUrl,
// //         "description": description,
// //       };
// // }







import 'package:hive/hive.dart';
import 'package:azan_guru_mobile/ui/model/media_node.dart';
import 'dart:convert';

part 'free_quran_data.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0)
class FreeQuranData {
  @HiveField(0)
  List<FreeQuranNode>? nodes;

  FreeQuranData({
    this.nodes,
  });

  factory FreeQuranData.fromJson(Map<String, dynamic> json) => FreeQuranData(
    nodes: json["nodes"] == null
        ? []
        : List<FreeQuranNode>.from(
        json["nodes"]!.map((x) => FreeQuranNode.fromJson(x))),
  );

  Map<String, dynamic> toJson() => {
    "nodes": nodes == null
        ? []
        : List<dynamic>.from(nodes!.map((x) => x.toJson())),
  };

  static FreeQuranData fromJsonString(String str) =>
      FreeQuranData.fromJson(json.decode(str));

  String toJsonString() => json.encode(toJson());
}

@HiveType(typeId: 1)
class FreeQuranNode {
  @HiveField(0)
  String? id;
  @HiveField(1)
  int? databaseId;
  @HiveField(2)
  DateTime? date;
  @HiveField(3)
  String? title;
  @HiveField(4)
  ListenQuran? listenQuran;

  FreeQuranNode({
    this.id,
    this.databaseId,
    this.date,
    this.title,
    this.listenQuran,
  });

  factory FreeQuranNode.fromJson(Map<String, dynamic> json) => FreeQuranNode(
    id: json["id"],
    databaseId: json["databaseId"],
    date: json["date"] == null ? null : DateTime.parse(json["date"]),
    title: json["title"],
    listenQuran: json["listenQuran"] == null
        ? null
        : ListenQuran.fromJson(json["listenQuran"]),
  );

  Map<String, dynamic> toJson() => {
    "id": id,
    "databaseId": databaseId,
    "date": date?.toIso8601String(),
    "title": title,
    "listenQuran": listenQuran?.toJson(),
  };
}

@HiveType(typeId: 2)
class ListenQuran {
  @HiveField(0)
  String? listenQuranDescription;
  @HiveField(1)
  QuranAudio? quranAudio;

  ListenQuran({
    this.listenQuranDescription,
    this.quranAudio,
  });

  factory ListenQuran.fromJson(Map<String, dynamic> json) => ListenQuran(
    listenQuranDescription: json["listenQuranDescription"],
    quranAudio: json["quranAudio"] == null
        ? null
        : QuranAudio.fromJson(json["quranAudio"]),
  );

  Map<String, dynamic> toJson() => {
    "listenQuranDescription": listenQuranDescription,
    "quranAudio": quranAudio?.toJson(),
  };
}

@HiveType(typeId: 3)
class QuranAudio {
  @HiveField(0)
  MediaNode? node;

  QuranAudio({
    this.node,
  });

  factory QuranAudio.fromJson(Map<String, dynamic> json) => QuranAudio(
    node: json["node"] == null ? null : MediaNode.fromJson(json["node"]),
  );

  Map<String, dynamic> toJson() => {
    "node": node?.toJson(),
  };
}
